---
# Composite Resource Definition (XRD)
apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: xmongodbs.platform.example.com
spec:
  # Create a namespaced resource (which is the default in Crossplane v2)
  # Valid options are: Namespaced, Cluster
  #scope: Namespaced
  group: platform.example.com
  names:
    kind: XMongoDB
    plural: xmongodbs
  claimNames:
    kind: MongoDB
    plural: mongodbs
  versions:
    - name: v1alpha1
      served: true
      referenceable: true
      schema:
        openAPIV3Schema:
          type: object
          required:
            - metadata
            - spec
          properties:
            metadata:
              type: object
              required:
                - name
              properties:
                name:
                  type: string
                  minLength: 1
                  maxLength: 63
                  example: my-cluster
                  pattern: '^[a-z]([-a-z0-9]*[a-z0-9])?$'
            spec:
              type: object
              required:
                - storageSize
              properties:
                storageSize:
                  title: 'Storage Size'
                  type: integer
                  minimum: 1
                  maximum: 100
                  example: 1
                  default: 10
            # Definition required to be able to patch the status field in composition
            status:
              type: object
              properties:
                connString:
                  type: string
                  example: mongodb+srv://<username>:<password>@example.mongodb.net/test